#!/bin/sh

: ${JGMENU_EXEC_DIR=~/src/jgmenu}

export PATH=$JGMENU_EXEC_DIR:$PATH
JGMENU_LOCKFILE=~/.jgmenu-lockfile

die () {
	printf "fatal: %s\n" "$1"
	exit 1
}

usage () {
	printf "usage: jgmenu_run\n"
	printf "       jgmenu_run <command> [<args>]\n\n"
	printf "Top level convenience wrapper for jgmenu\n\n"
	printf "If no 'command' or argument is specified, jgmenu_run does one of the following:\n"
	printf "  - Shows the menu if an instance of jgmenu is already running\n"
	printf "  - Starts jgmenu in 'stay-alive' mode (i.e. as a long-running application)\n"
	printf "    using pmenu unless otherwise specified by 'csv_cmd' in jgmenurc\n\n"
	printf "Valid 'commands' include:\n"
	printf "    start           Start menu in 'hidden' mode\n"
	printf "    re-start        Re-start jgmenu to read config file and load new apps\n"
	printf "    pmenu           Run menu based on .desktop and .directory files\n"
	printf "    xdg             Run menu based on .desktop, .directory and .menu files\n"
	printf "    csv             Run menu based on .csv file\n"
	printf "    cache           Create icon cache\n\n"
	exit 0
}

# Pipe to UNIX socket if tint2 button was used.
send_tint2_env_vars_to_jgmenu () {
	# Check set/unset with ${parameter+word}
	test -z ${TINT2_BUTTON_ALIGNED_X+x} && return
	printf "%b" \
		"TINT2_BUTTON_ALIGNED_X1=${TINT2_BUTTON_ALIGNED_X1}\n" \
		"TINT2_BUTTON_ALIGNED_X2=${TINT2_BUTTON_ALIGNED_X2}\n" \
		"TINT2_BUTTON_ALIGNED_Y1=${TINT2_BUTTON_ALIGNED_Y1}\n" \
		"TINT2_BUTTON_ALIGNED_Y2=${TINT2_BUTTON_ALIGNED_Y2}\n" \
		"TINT2_BUTTON_PANEL_X1=${TINT2_BUTTON_PANEL_X1}\n" \
		"TINT2_BUTTON_PANEL_X2=${TINT2_BUTTON_PANEL_X2}\n" \
		"TINT2_BUTTON_PANEL_Y1=${TINT2_BUTTON_PANEL_Y1}\n" \
		"TINT2_BUTTON_PANEL_Y2=${TINT2_BUTTON_PANEL_Y2}" \
		| ${JGMENU_EXEC_DIR}/jgmenu-socket
}

# "jgmenu_run" with no arguments specified
if test $# -lt 1
then
	# A primary objective here is to keep 'awake' quick
	# Checking if the lockfile exists is much quicker than
	# 'pgrep -x jgmenu' (30ms on my machine) or similar.
	if test -e ${JGMENU_LOCKFILE}
	then
		send_tint2_env_vars_to_jgmenu
		killall -SIGUSR1 jgmenu >/dev/null 2>&1
	else
		cmd=$(jgmenu_run config --get csv_cmd)
		test -z "${cmd}" && cmd="jgmenu_run parse-pmenu"

		# Run it through a shell enable tilde and variable expansion
		sh -c "${cmd} | jgmenu --stay-alive"
	fi
	exit 0
fi

test "$1" = "--help" && usage

cmd="$1"
cmds="jgmenu-${cmd} jgmenu-${cmd}.sh jgmenu-${cmd}.py"
shift

for c in ${cmds}
do
	if type ${c} >/dev/null 2>&1
	then
		exec ${c} "$@"
		exit 0
	fi
done

die "'${cmd}' is not a jgmenu_run command"
