#!/bin/sh

: ${JGMENU_EXEC_DIR=~/src/jgmenu}

export PATH=$JGMENU_EXEC_DIR:$PATH

die () {
	printf "fatal: %s\n" "$1"
	exit 1
}

usage () {
	printf "usage: jgmenu_run <command> [<args>]\n"
	printf "\n"
	printf "Top level convenience wrapper for jgmenu\n"
	printf "\n"
	printf "Valid 'commands' include:\n"
	printf "    pmenu           Menu based on .directory and .desktop files\n"
	printf "    xdg             Menu based on .menu file\n"
	printf "    csv             Menu based on .csv file\n"
	printf "    cache           Create icon cache\n"
	printf "\n"
	exit 0
}



if test $# -lt 1
then
	usage
fi

cmd="$1"
cmds="jgmenu-${cmd} jgmenu-${cmd}.sh jgmenu-${cmd}.py"
shift

for c in ${cmds}
do
	if type ${c} >/dev/null 2>&1
	then
		exec ${c} "$@"
		exit 0
	fi
done

die "'${cmd}' is not a jgmenu_run command"
