#!/bin/bash

(
echo -e 'ROOT MENU,^tag(root)'
echo -e 'terminal,xterm'
echo -e 'browser,firefox'
echo -e 'file manager,pcmanfm'
echo -e 'config,^checkout(config)'
echo -e 'CONFIG,^tag(config)'
echo -e '..,^checkout(root)'
echo -e 'background,nitrogen ~/bg/'
echo -e 'item1,xterm'
echo -e 'item2,xterm'
echo -e 'item3,xterm'
echo -e 'item4,xterm'
echo -e 'item5,xterm'
echo -e 'item6,xterm'
echo -e 'item7,xterm'
echo -e 'item8,xterm'
echo -e 'item9,xterm'
echo -e 'item10,xterm'
echo -e 'item11,xterm'
echo -e 'item12,xterm'
echo -e 'item13,xterm'
echo -e 'item14,xterm'
echo -e 'item15 (last),xterm'
) | ../jgmenu --config-file=./jgmenurc
