.TH "JGMENU\-PMENU(1)
.PD 0
.P
.PD
% Johan Malm
.PD 0
.P
.PD
% 17 December, 2017
.SH NAME
.PP
jgmenu\-pmenu.py \- generates a menu based on .desktop and .directory
.PD 0
.P
.PD
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ files found on the system.
.SH SYNOPSIS
.PP
jgmenu_run pmenu [\-h | \-\-help] [\-\-append\-file <\f[I]FILE\f[]>]
.PD 0
.P
.PD
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ [\-\-prepend\-file <\f[I]FILE\f[]>]
[\-\-locale <\f[I]LOCALE\f[]>]
.SH DESCRIPTION
.PP
Generates jgmenu flavoured CSV text based on .desktop and .directory
.PD 0
.P
.PD
files found on the system, but ignores any .menu files.
Instead of
.PD 0
.P
.PD
the structure specified in the .menu file, it simply maps each
.PD 0
.P
.PD
".desktop" application onto one of the ".directory" categories.
If a
.PD 0
.P
.PD
matching ".directory" category does not exist, it tries to
.PD 0
.P
.PD
cross\-reference "additional categories" to "related categories" in
.PD 0
.P
.PD
accordance with the XDG menu\-spec.
This is a generic approach which
.PD 0
.P
.PD
avoids Desktop Environment specific rules defined in the .menu file.
.PD 0
.P
.PD
It ensures that all .desktop files are included in the menu.
.PP
The root menu is appended/prepended by the contents of the following
.PD 0
.P
.PD
files if they exist:
.IP
.nf
\f[C]
~/.config/jgmenu/append.csv\ \ 
~/.config/jgmenu/prepend.csv\ \ 
\f[]
.fi
.SH OPTIONS
.TP
.B \-h, \-\-help
show this help message and exit
.RS
.RE
.TP
.B \-\-append\-file FILE
Path to menu file to append to the root menu
.RS
.RE
.TP
.B \-\-prepend\-file FILE
Path to menu file to prepend to the root menu
.RS
.RE
.TP
.B \-\-locale LOCALE
Use a custom locale (e.g.
\[aq]en_US.UTF\-8\[aq]; available
.PD 0
.P
.PD
.RS
.RE
.PP
\ \ \ \ \ \ \ locales can be shown by running \[aq]locale \-a\[aq])
.SH EXAMPLES
.PP
This program is designed to be run from jgmenu by settings
.PD 0
.P
.PD
\f[C]csv_cmd\ =\ pmenu\f[] in the configuration file (jgmenurc).
.PP
It can also be run directly from the command line like this:
.IP
.nf
\f[C]
jgmenu_run\ pmenu\ |\ jgmenu

jgmenu\ \-\-csv\-cmd="jgmenu_run\ pmenu"
\f[]
.fi
