.TH "JGMENU\-XDG(1)
.PD 0
.P
.PD
% Johan Malm
.PD 0
.P
.PD
% 17 December, 2017
.SH NAME
.PP
jgmenu\-xdg.sh \- generates jgmenu flavoured CSV for an XDGish menu
.SH SYNOPSIS
.PP
\f[C]jgmenu_run\ xdg\f[] [\-\-no\-dirs] [<\f[I]\&.menu file\f[]>]
.SH DESCRIPTION
.PP
\f[C]jgmenu_run\ xdg\f[] generates jgmenu flavoured CSV text for a menu
based
.PD 0
.P
.PD
on XML .menu files loosely in accordance with the XDG specifications:
.PP
http://standards.freedesktop.org/menu\-spec/
.PD 0
.P
.PD
http://standards.freedesktop.org/basedir\-spec/
.PD 0
.P
.PD
http://standards.freedesktop.org/desktop\-entry\-spec/
.PD 0
.P
.PD
http://standards.freedesktop.org/desktop\-entry\-spec/
.PP
\f[C]jgmenu_run\ xdg\f[] is a very simple XDG implementation.
.PD 0
.P
.PD
It understands the XML elements <\f[I]Menu\f[]>, <\f[I]Name\f[]>,
<\f[I]Directory\f[]>
.PD 0
.P
.PD
and <\f[I]Include\f[]><\f[I]And\f[]><\f[I]Category\f[]>, but ignores
everything else.
.PP
The .menu file is sought in \f[C]${XDG_CONFIG_DIRS:\-/etc/xdg}\f[] with
.PD 0
.P
.PD
user configuration override in
\f[C]${XDG_CONFIG_HOME:\-$HOME/.config}\f[]
.PP
\f[C]$XDG_MENU_PREFIX\f[] can be used to specity a .menu file.
For example
.PD 0
.P
.PD
\f[C]$XDG_MENU_PREFIX=lxde\-\f[] will load lxde\-applications.menu
.PD 0
.P
.PD
This can be useful if there are several .menu files on the system.
.SH OPTIONS
.TP
.B \-\-no\-dirs
ignore .menu and .directory files
.RS
.RE
.SH EXAMPLES
.IP
.nf
\f[C]
jgmenu_run\ xdg
\f[]
.fi
