-include ../../config.mk
include ../../Makefile.inc

pmenu:
	@:

install:
	@install -d $(DESTDIR)$(libexecdir)
	@install -m775 jgmenu-pmenu.py $(DESTDIR)$(libexecdir)

uninstall:
	@rm -f $(libexecdir)/jgmenu-pmenu.py

clean:
